### ISSUE TITLE
`TSDX_README.md` instructions not working

### ISSUE THREAD

**Issue by nh2** [TimboKZ/Chonky#165]
I'm trying to follow `packages/chonky/TSDX_README.md`, but it seems outdated:

    ### Storybook

    Run inside another terminal:

    ```bash
    yarn storybook
    ```

This doesn't work, gives `error Command "storybook" not found.`

Further,

    ### Example

    Then run the example inside another:

    ```bash
    cd example
    npm i # or yarn to install dependencies
    npm start # or yarn start
    ```

produces error `Invalid Version: undefined`:

```
% yarn start
yarn run v1.22.18
$ parcel index.html
Server running at http://localhost:1234 
⠸ Building index.tsx...Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
🚨  /home/niklas/src/Chonky/packages/chonky/example/index.tsx: Invalid Version: undefined
    at new SemVer (/home/niklas/src/Chonky/packages/chonky/example/node_modules/semver/semver.js:314:11)
    at compare (/home/niklas/src/Chonky/packages/chonky/example/node_modules/semver/semver.js:647:10)
    at lt (/home/niklas/src/Chonky/packages/chonky/example/node_modules/semver/semver.js:688:10)
    at /home/niklas/src/Chonky/packages/chonky/example/node_modules/@babel/preset-env/lib/index.js:280:22
    at Object.default (/home/niklas/src/Chonky/packages/chonky/example/node_modules/@babel/helper-plugin-utils/lib/index.js:22:12)
    at getEnvPlugins (/home/niklas/src/Chonky/packages/chonky/example/node_modules/parcel/src/transforms/babel/env.js:62:34)
    at getEnvConfig (/home/niklas/src/Chonky/packages/chonky/example/node_modules/parcel/src/transforms/babel/env.js:12:25)
    at async getBabelConfig (/home/niklas/src/Chonky/packages/chonky/example/node_modules/parcel/src/transforms/babel/config.js:32:19)
    at async babelTransform (/home/niklas/src/Chonky/packages/chonky/example/node_modules/parcel/src/transforms/babel/transform.js:6:16)
    at async JSAsset.pretransform (/home/niklas/src/Chonky/packages/chonky/example/node_modules/parcel/src/assets/JSAsset.js:83:5)
```

**Comment by TimboKZ** [comment]
`TSDX_README.md` was never meant to work, it's just something TSDX generated by default when I setup the TSDX project. I will remove it shortly (soon Chonky won't be using TSDX anyway).
