### ISSUE TITLE
yarn build result in error

### ISSUE THREAD

**Issue by ww8912188** [TimboKZ/Chonky#63]
Hi guys,

I'm using chonky@2.1.0 and it result in below error during yarn build:

```
➜  frontend git:(feature/server-dir) ✗ yarn build
yarn run v1.22.4
$ GENERATE_SOURCEMAP=false react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the bundle. Error: static/js/main.89e8c67b.js from UglifyJs
Unexpected token: name (FuzzySearch) [static/js/main.89e8c67b.js:110354,6]
    at /Users/user/gitlab/frontend/node_modules/react-scripts/scripts/build.js:128:23
    at /Users/user/gitlab/frontend/node_modules/webpack/lib/Compiler.js:269:13
    at Compiler.emitRecords (/Users/user/gitlab/frontend/node_modules/webpack/lib/Compiler.js:375:38)
    at /Users/user/gitlab/frontend/node_modules/webpack/lib/Compiler.js:262:10
    at /Users/user/gitlab/frontend/node_modules/webpack/lib/Compiler.js:368:12
    at next (/Users/user/gitlab/frontend/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.<anonymous> (/Users/user/gitlab/frontend/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at next (/Users/user/gitlab/frontend/node_modules/tapable/lib/Tapable.js:220:14)
    at /Users/user/gitlab/frontend/node_modules/sw-precache-webpack-plugin/lib/index.js:98:18
Read more here: http://bit.ly/2tRViJ9
```

Here is the static/js/main.89e8c67b.js:110354,6 info:
![image](https://user-images.githubusercontent.com/17057416/104929843-60b53700-59df-11eb-933d-5f1bfe69d83e.png)

Here is my version info:
```
"chonky": "^2.1.0",
"chonky-icon-fontawesome": "^2.1.0",
"react": "^17.0.0",
"react-dom": "^17.0.0",
```

I searched all over with no luck. It will be great if someone could shine some light on this issue.

**Comment by TimboKZ** [comment]
Hi, I have not encountered this problem before, but it seems it has something to do with ES5 transpilation target.

Does this help at all? https://stackoverflow.com/questions/33042084/es6-classes-unexpected-token-in-script

**Comment by ww8912188** [comment]
I'm using a very old version of create-react-app(v1.1.5). The issue is gone after I upgrated it to v4.0.5.
Thanks TimboKZ all the same. Close the issue.
